# Generated by Django 4.0.6 on 2022-07-31 19:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_do_not_email_alter_user_do_not_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gps_address',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_of_children',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
