# Generated by Django 4.0.6 on 2022-07-26 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('mark_as_private', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_type', models.CharField(blank=True, choices=[('visit', 'visit'), ('text', 'text'), ('call', 'call'), ('email', 'email')], max_length=6, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('care', 'care'), ('ceremony', 'ceremony'), ('other', 'other')], max_length=10, null=True)),
                ('done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('people', models.ManyToManyField(blank=True, help_text='Select one or more members to make follow up on. Could be new members, sick members etc', related_name='members_set', related_query_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
            },
        ),
    ]
