# Generated by Django 3.2.6 on 2022-10-18 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_type', models.CharField(blank=True, choices=[('visit', 'visit'), ('text', 'text'), ('call', 'call'), ('email', 'email')], max_length=6, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('care', 'care'), ('ceremony', 'ceremony'), ('other', 'other')], max_length=10, null=True)),
                ('done', models.BooleanField(default=False)),
                ('notes', tinymce.models.HTMLField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('mark_as_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
