# Generated by Django 3.2.6 on 2022-10-18 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='Select one or more members to make follow up on. Could be new members, sick members etc', related_name='members_set', related_query_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
