# Generated by Django 4.0.6 on 2022-07-31 19:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
